PRAGMA foreign_keys = ON;

CREATE TABLE users(
  -- userid INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(20) PRIMARY KEY,
  fullname VARCHAR(20) NOT NULL,
  email VARCHAR(40) NOT NULL,
  password VARCHAR(256) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE restaurants(
  restid INTEGER PRIMARY KEY AUTOINCREMENT,
  location VARCHAR(64) NOT NULL,
  name VARCHAR(20) NOT NULL,
  adder VARCHAR(20) NOT NULL,
  goodexp BOOLEAN NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(adder) REFERENCES users(username) ON DELETE CASCADE
);

CREATE TABLE symptoms(
  dateid INTEGER PRIMARY KEY AUTOINCREMENT,
  adder VARCHAR(20) NOT NULL,
  day INTEGER NOT NULL,
  month INTEGER NOT NULL,
  year INTEGER NOT NULL,
  type VARCHAR(20) NOT NULL,
  notes VARCHAR(200) NOT NULL,
  FOREIGN KEY(adder) REFERENCES users(username) ON DELETE CASCADE
);

-- CREATE TABLE journal(
--   symptomid INTEGER PRIMARY KEY AUTOINCREMENT,
--   adder VARCHAR(20) NOT NULL,
--   day INTEGER NOT NULL,
--   month INTEGER NOT NULL,
--   year INTEGER NOT NULL,
--   meal VARCHAR(20) NOT NULL,
--   name VARCHAR(20) NOT NULL,

--   FOREIGN KEY(adder) REFERENCES users(username) ON DELETE CASCADE
-- );
