PRAGMA foreign_keys = ON;

CREATE TABLE users(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(20) NOT NULL,
  fullname VARCHAR(20) NOT NULL,
  email VARCHAR(40) NOT NULL,
  password VARCHAR(256) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE restaurants(
  postid INTEGER PRIMARY KEY AUTOINCREMENT,
  location VARCHAR(64) NOT NULL,
  name VARCHAR(20) NOT NULL,
  adder VARCHAR(20) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(adder) REFERENCES users(id) ON DELETE CASCADE
);


